### ISSUE TITLE
Is there any reason you didn't use NLog.ILogger as service interface

### ISSUE THREAD

**Issue by wossig** [Trendyol/AutoFac.Extras.NLog.DotNetCore#1]
First,  it's very nice to see .NET Core one to bind AutoFac, but you didn't use NLog.ILogger, do you have specific reason?

As I know [Autofac.Extras.NLog](https://github.com/ziyasal/Autofac.Extras.NLog) already moved to NLog.ILogger.

It just confused me,  I have a .NET Framework(4.7.5) project and new project with .NET Core both using same standard library(as my plan, I want migrate all .NET Framework project  to core), and  the standard library using **NLog.ILog** as service injected,  I'm very happy to see  your .Net Core implantation 😀,  unluckily, I can't use it directly, so I just want know, **do you had met any issue while using NLog.ILogger?**  it seems very sample to wrapper class **LoggerAdapter**

and I saw your comments, seems here have some issue:
```csharp
//INFO: ADAPTED FROM NLOG:INTERFACE Project https://github.com/uhaciogullari/NLog.Interface
//TODO: UPDATE TO USE NLOG:INTERFACE Package (Fork and solve nlog.interface issues)
```

**Comment by peacecwz** [comment]
Yeah, We ported our API projects .NET Framework to .NET Core. When we ported projects, We didn't upgrade any dependencies if not needed for stabilization. Now, We don't use NLog. We are using Microsoft.Extensions.Logging for .NET Core projects and we suggest it

I'm answering as a Checkout team from Trendyol :)
